import { Montserrat, Inter } from "next/font/google"
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./(components)/header";

const montserrat = Montserrat({
  weight: ["400", "500", "600"],
  subsets: ["latin"]
})

const inter = Inter({
  weight: ["400", "500"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Climatize",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${montserrat} ${inter} antialiased`}
      >
        <Header />
        <main className="bg-main flex-grow">{children}</main>
      </body>
    </html>
  );
}
